### ISSUE TITLE
Moving to LSL module

### ISSUE THREAD

**Issue by Yida-Lin** [Yida-Lin/XDFStreamer#8]
Moving to LSL module

**Comment by Yida-Lin** [comment]
Hi @cboulay would you be interested in taking this project into xdf-modules or LSL as well? Thanks

**Comment by cboulay** [comment]
Yes that would be great! I think it belongs more in github.com/labstreaminglayer more than /xdf-modules.

**Comment by Yida-Lin** [comment]
@cboulay OK! I will transfer to you then.

**Comment by cboulay** [comment]
Done. Thank you! You're back as an admin on the repo.

**Comment by Yida-Lin** [comment]
@cboulay Great!
